# Generated by Django 5.1.3 on 2024-11-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='users',
        ),
    ]
