# Generated by Django 5.1.3 on 2024-11-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_remove_device_users'),
        ('post_receiver', '0008_devicedata_alarm_status_devicedata_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicepermission',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_receiver.devicedata'),
        ),
    ]
