# Generated by Django 5.1.3 on 2024-11-29 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDash', '0003_devicegroup'),
        ('access_control', '0003_alter_devicepermission_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage', models.BooleanField(default=True)),
                ('device_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDash.devicegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Разрешение на группу устройств',
                'verbose_name_plural': 'Разрешения на группы устройств',
                'unique_together': {('user', 'device_group')},
            },
        ),
    ]
