# Generated by Django 5.1.3 on 2024-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDash', '0005_eventnotification'),
        ('access_control', '0004_devicegrouppermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255, verbose_name='Название района')),
                ('groups', models.ManyToManyField(related_name='districts', to='UserDash.devicegroup', verbose_name='Группы домов')),
            ],
        ),
    ]
