# Generated by Django 5.1.3 on 2024-12-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_alter_districtgroup_district_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtgroup',
            name='district_name',
            field=models.CharField(max_length=255, verbose_name='Название района (ТСЖ, УК, ТСН, ЖСК)'),
        ),
    ]
