# Generated by Django 5.1.3 on 2024-12-05 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0008_alter_districtgroup_district_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage', models.BooleanField(default=False, verbose_name='Может управлять')),
                ('district_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='access_control.districtgroup', verbose_name='Район')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
