# Generated by Django 5.1.3 on 2024-12-05 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_districtgrouppermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('users', models.ManyToManyField(related_name='custom_user_groups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
    ]
