# Generated by Django 5.1.3 on 2024-11-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDash', '0002_notification_dev_eui'),
        ('post_receiver', '0008_devicedata_alarm_status_devicedata_altitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('address', models.TextField(verbose_name='Адрес группы')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта группы')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота группы')),
                ('devices', models.ManyToManyField(related_name='device_groups', to='post_receiver.devicedata', verbose_name='Устройства')),
            ],
        ),
    ]
