# Generated by Django 5.1.3 on 2024-11-29 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDash', '0003_devicegroup'),
        ('post_receiver', '0008_devicedata_alarm_status_devicedata_altitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_groups', models.ManyToManyField(blank=True, related_name='users_groups', to='UserDash.devicegroup')),
                ('devices', models.ManyToManyField(blank=True, related_name='users_individual', to='post_receiver.devicedata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
