# Generated by Django 5.1.3 on 2024-11-30 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDash', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(blank=True, max_length=255, null=True, verbose_name='DevEUI')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('notification_type', models.CharField(choices=[('warning', 'Предупреждение'), ('success', 'Успех'), ('error', 'Ошибка'), ('info', 'Информация'), ('system', 'Системное')], default='info', max_length=20, verbose_name='Тип уведомления')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
