# Generated by Django 5.1.3 on 2024-12-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDash', '0005_eventnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnotification',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
