"""
Django settings for skudlora project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$a+&e8uzbl*q+*-mfsbhjr5e@302^nb1(0dy))myhyjfe#_(rj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'access_control',
    'rest_framework',
    'post_receiver',
    'UserDash',
    'post_receiver.authconfig.CustomAuthConfig', #ЕСЛИ что это кастом 'django.contrib.auth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skudlora.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
        os.path.join(BASE_DIR, 'access_control/templates', 'UserDash/templates')
        ],
        'APP_DIRS': False,
        'OPTIONS': {
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',  # Если нужно использовать шаблоны из приложений                
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        },
    },
]

WSGI_APPLICATION = 'skudlora.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CMS_COLOR_SCHEME_TOGGLE = True
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

#ADMIN_TOOLS_THEMING_CSS = 'css/theming.css'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_cdn")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGOUT_REDIRECT_URL = '/'


JAZZMIN_SETTINGS = {
"site_brand": "SELIO",   
"show_ui_builder": False,
"show_sidebar": True,
"site_logo": "/books/img/OnPhone.png",
"user_avatar": None,
"copyright": "ООО \"Пэск\"",
"navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "post_receiver.devicedata": "fa-solid fa-plus",
        "post_receiver.apikey": "fa-solid fa-key",
    },
    "hide_models": [
        "UserDash.DeviceGroup",
        "Access_Control.districtgroup", 
        "auth.Group",
    ],

        "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Домой",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        {"name": "DashBoard", "url": "/UserDash/index/", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "books"},
    ],
    
    "custom_links": {
        ##"auth": [{
        #    "name": "Отправить ХУЙ",
        #№}],
        
        "post_receiver": [
        {
            "name": "Редактор групп устройств",
            "url": "/admin/UserDash/devicegroup/",
            "icon": "fas fa-layer-group"
        },
        {
            "name": "Редактор районов",
            "url": "/admin/access_control/districtgroup/",
            "icon": "fas fa-sitemap"
        },             
        {
            "name": "Отправить HEX",
            "url": "/post_receiver/hex_sent/",
            "icon": "fa-solid fa-upload"
        },  
        {
            "name": "Объеденинение устройств и пользователей",
            "url": "/edit_device_permissions/",
            "icon": "fa-solid fa-tower-cell"
        },
        {
            "name": "Объеденинение домов и пользователей",
            "url": "/device-group-permissions/",
            "icon": "fa-solid fa-building"
        },
        {
            "name": "Объеденинение районов и пользователей",
            "url": "/edit_user_district_permissions/",
            "icon": "fa-solid fa-city"
        },          
        ],
        "auth": [
        {
            "name": "Объеденинение пользователей",
            "url": "/manage_user_groups/",
            "icon": "fa-solid fa-people-group"
        },             
        ],
    },
    
}



JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-info",
    "accent": "accent-info",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "slate",
    "dark_mode_theme": "slate",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    },
    "actions_sticky_top": False
}