# Generated by Django 5.1.3 on 2024-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('dev_eui', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('time', models.DateTimeField()),
                ('rssi', models.IntegerField(null=True)),
                ('lo_ra_snr', models.IntegerField(null=True)),
            ],
        ),
    ]
