# Generated by Django 5.1.3 on 2024-11-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='device_class',
            field=models.CharField(choices=[('NbIot', 'NbIot'), ('LoRaWAN', 'LoRaWAN')], default='NbIot', max_length=10),
        ),
    ]
