# Generated by Django 5.1.3 on 2024-11-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_receiver', '0004_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='key_name',
            field=models.CharField(default='Не указано', max_length=255, verbose_name='Название ключа'),
        ),
    ]
