# Generated by Django 5.1.3 on 2024-11-21 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_receiver', '0005_apikey_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post_receiver.apikey', verbose_name='API Ключ'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_name',
            field=models.CharField(default='Введите название, указанное на сайте поставщика услуг', max_length=255, verbose_name='Название ключа'),
        ),
    ]
