# Generated by Django 4.0 on 2024-11-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('dev_eui', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('time', models.DateTimeField()),
                ('rssi', models.IntegerField(null=True)),
                ('lo_ra_snr', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('device_class', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'device_data',
            },
        ),
    ]
